/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.arunkumar.sample

import com.google.auto.service.AutoService
import dagger.model.BindingGraph
import dagger.spi.BindingGraphPlugin
import dagger.spi.DiagnosticReporter
import guru.nidi.graphviz.*
import guru.nidi.graphviz.attribute.Arrow
import guru.nidi.graphviz.attribute.Color
import guru.nidi.graphviz.attribute.RankDir
import guru.nidi.graphviz.engine.Format
import javax.annotation.processing.Filer
import javax.lang.model.util.Elements
import javax.lang.model.util.Types
import javax.tools.StandardLocation

@AutoService(BindingGraphPlugin::class)
class ScabbardBindingGraphPlugin : BindingGraphPlugin {

    private lateinit var filer: Filer
    private lateinit var types: Types
    private lateinit var elements: Elements

    override fun initFiler(filer: Filer) {
        this.filer = filer
    }

    override fun initTypes(types: Types) {
        this.types = types
    }

    override fun initElements(elements: Elements) {
        this.elements = elements
    }

    override fun visitGraph(bindingGraph: BindingGraph, diagnosticReporter: DiagnosticReporter) {
        println(bindingGraph.toString())
        graph(directed = true) {
            edge["color" eq "red", Arrow.TEE]
            node[Color.GREEN]
            graph[RankDir.LEFT_TO_RIGHT]
            "a" - "b" - "c"
            ("c"[Color.RED] - "d"[Color.BLUE])[Arrow.VEE]
        }.toGraphviz().render(Format.PNG).toOutputStream(
            filer.createResource(
                StandardLocation.CLASS_OUTPUT,
                "test",
                "x.png"
            ).openOutputStream()
        )
    }
}