/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.arunkumar.scabbard

import org.gradle.testfixtures.ProjectBuilder
import org.junit.Test

/**
 * A simple unit test for the 'dev.arunkumar.scabbard.greeting' plugin.
 */
class ScabbardGradlePluginPluginTest {
  @Test
  fun `plugin registers task`() {
    val project = ProjectBuilder.builder().build()
    project.plugins.apply("scabbard-gradle-plugin")
  }
}