/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.arunkumar.scabbard

import com.google.common.truth.Truth
import dev.arunkumar.scabbard.gradle.ScabbardGradlePlugin.Companion.SCABBARD_PLUGIN_ID
import org.gradle.testfixtures.ProjectBuilder
import org.junit.Test

/**
 * A simple unit test for the 'dev.arunkumar.scabbard.greeting' plugin.
 */
class ScabbardGradlePluginPluginTest {
  @Test
  fun `project applies plugin`() {
    val project = ProjectBuilder.builder().build()
    project.plugins.apply(SCABBARD_PLUGIN_ID)
    Truth.assertThat(project.plugins.getPlugin(SCABBARD_PLUGIN_ID)).isNotNull()
  }
}